// <auto-generated />
using System;
using EsiaUserGenerator.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EsiaUserGenerator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251204224435_UpdateSchemaOneToOne")]
    partial class UpdateSchemaOneToOne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EsiaUserGenerator.Db.Models.EsiaUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Oid")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedRequestId")
                        .IsUnique();

                    b.ToTable("EsiaUsers", (string)null);
                });

            modelBuilder.Entity("EsiaUserGenerator.Db.Models.RequestHistory", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Finished")
                        .HasColumnType("boolean");

                    b.Property<string>("JsonRequest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RequestId");

                    b.ToTable("RequestHistory", (string)null);
                });

            modelBuilder.Entity("EsiaUserGenerator.Db.Models.EsiaUser", b =>
                {
                    b.HasOne("EsiaUserGenerator.Db.Models.RequestHistory", "RequestData")
                        .WithOne("User")
                        .HasForeignKey("EsiaUserGenerator.Db.Models.EsiaUser", "CreatedRequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("RequestData");
                });

            modelBuilder.Entity("EsiaUserGenerator.Db.Models.RequestHistory", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
