// <auto-generated />
using System;
using EsiaUserGenerator.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EsiaUserGenerator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251120154717_FixModelChanges")]
    partial class FixModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EsiaUserGenerator.Db.Models.CreatedHistory", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "CreatedRequestId");

                    b.ToTable("CreatedHistory", (string)null);
                });

            modelBuilder.Entity("EsiaUserGenerator.Db.Models.EsiaUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Oid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EsiaUsers", (string)null);
                });

            modelBuilder.Entity("EsiaUserGenerator.Db.Models.RequestHistory", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("JsonRequest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "RequestId");

                    b.ToTable("RequestHistory", (string)null);
                });

            modelBuilder.Entity("EsiaUserGenerator.Db.Models.CreatedHistory", b =>
                {
                    b.HasOne("EsiaUserGenerator.Db.Models.EsiaUser", "User")
                        .WithMany("CreatedHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EsiaUserGenerator.Db.Models.RequestHistory", b =>
                {
                    b.HasOne("EsiaUserGenerator.Db.Models.EsiaUser", "User")
                        .WithMany("RequestHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EsiaUserGenerator.Db.Models.EsiaUser", b =>
                {
                    b.Navigation("CreatedHistories");

                    b.Navigation("RequestHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
