// <auto-generated />
using System;
using EsiaUserGenerator.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EsiaUserGenerator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251205212521_AddEsiaInfoGeneratedData_ArrayFix")]
    partial class AddEsiaInfoGeneratedData_ArrayFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EsiaUserGenerator.Db.Models.EsiaUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Oid")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedRequestId")
                        .IsUnique();

                    b.ToTable("EsiaUsers", (string)null);
                });

            modelBuilder.Entity("EsiaUserGenerator.Db.Models.RequestHistory", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Finished")
                        .HasColumnType("boolean");

                    b.Property<string>("JsonRequest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RequestId");

                    b.ToTable("RequestHistory", (string)null);
                });

            modelBuilder.Entity("EsiaUserGenerator.Db.Models.EsiaUser", b =>
                {
                    b.HasOne("EsiaUserGenerator.Db.Models.RequestHistory", "RequestData")
                        .WithOne("User")
                        .HasForeignKey("EsiaUserGenerator.Db.Models.EsiaUser", "CreatedRequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("RequestData");
                });

            modelBuilder.Entity("EsiaUserGenerator.Db.Models.RequestHistory", b =>
                {
                    b.OwnsOne("EsiaUserGenerator.Dto.Model.EsiaUserInfo", "GeneratedUserInfo", b1 =>
                        {
                            b1.Property<Guid>("RequestHistoryRequestId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("BirthDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("BirthPlace")
                                .HasColumnType("text");

                            b1.Property<string>("Citizenship")
                                .HasColumnType("text");

                            b1.Property<string>("FirstName")
                                .HasColumnType("text");

                            b1.Property<string>("Gender")
                                .HasColumnType("text");

                            b1.Property<string>("LastName")
                                .HasColumnType("text");

                            b1.Property<string>("Snils")
                                .HasColumnType("text");

                            b1.HasKey("RequestHistoryRequestId");

                            b1.ToTable("RequestHistory");

                            b1.ToJson("GeneratedUserInfo");

                            b1.WithOwner()
                                .HasForeignKey("RequestHistoryRequestId");

                            b1.OwnsOne("EsiaUserGenerator.Dto.Model.EsiaUserInfo+DocumentsInfo", "Documents", b2 =>
                                {
                                    b2.Property<Guid>("EsiaUserInfoRequestHistoryRequestId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("EsiaUserInfoRequestHistoryRequestId");

                                    b2.ToTable("RequestHistory");

                                    b2.WithOwner()
                                        .HasForeignKey("EsiaUserInfoRequestHistoryRequestId");

                                    b2.OwnsMany("EsiaUserGenerator.Dto.Model.EsiaUserInfo+DocumentsInfo+Element", "Elements", b3 =>
                                        {
                                            b3.Property<Guid>("DocumentsInfoEsiaUserInfoRequestHistoryRequestId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            b3.Property<DateTime?>("IssueDate")
                                                .HasColumnType("timestamp with time zone");

                                            b3.Property<string>("IssueId")
                                                .HasColumnType("text");

                                            b3.Property<string>("IssuedBy")
                                                .HasColumnType("text");

                                            b3.Property<string>("Number")
                                                .HasColumnType("text");

                                            b3.Property<string>("Series")
                                                .HasColumnType("text");

                                            b3.Property<string>("Type")
                                                .HasColumnType("text");

                                            b3.HasKey("DocumentsInfoEsiaUserInfoRequestHistoryRequestId", "__synthesizedOrdinal");

                                            b3.ToTable("RequestHistory");

                                            b3.WithOwner()
                                                .HasForeignKey("DocumentsInfoEsiaUserInfoRequestHistoryRequestId");
                                        });

                                    b2.Navigation("Elements");
                                });

                            b1.Navigation("Documents");
                        });

                    b.Navigation("GeneratedUserInfo");
                });

            modelBuilder.Entity("EsiaUserGenerator.Db.Models.RequestHistory", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
