// <auto-generated />
using System;
using EsiaUserGenerator.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EsiaUserGenerator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251203195920_RenameFieldsFix")]
    partial class RenameFieldsFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EsiaUserGenerator.Db.Models.EsiaUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Oid")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedRequestId");

                    b.ToTable("EsiaUsers", (string)null);
                });

            modelBuilder.Entity("EsiaUserGenerator.Db.Models.UserRequestHistory", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("JsonRequest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RequestId");

                    b.ToTable("RequestHistory", (string)null);
                });

            modelBuilder.Entity("EsiaUserGenerator.Db.Models.EsiaUser", b =>
                {
                    b.HasOne("EsiaUserGenerator.Db.Models.UserRequestHistory", "RequestData")
                        .WithMany("GeneratedProfiles")
                        .HasForeignKey("CreatedRequestId");

                    b.Navigation("RequestData");
                });

            modelBuilder.Entity("EsiaUserGenerator.Db.Models.UserRequestHistory", b =>
                {
                    b.Navigation("GeneratedProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
